{{- if .Values.todoapp.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-service-monitor
  namespace: {{ .Values.todoapp.namespace }}
  labels:
    release: {{ .Values.todoapp.serviceMonitor.labels.release }}
    app: {{ .Values.todoapp.serviceMonitor.labels.app }}
spec:
  jobLabel: job
  endpoints:
    - interval: {{ .Values.todoapp.serviceMonitor.interval }}
      port: {{ .Values.todoapp.serviceMonitor.port }}
      path: {{ .Values.todoapp.serviceMonitor.path }}
  selector:
    matchLabels:
      app: service-api
{{- end }}